
/*
	select * from fact.FbLnView_Base	
*/

IF OBJECT_ID(N'fact.Refined_MultiClient_FbLn') IS NOT NULL
    DROP view fact.Refined_MultiClient_FbLn
GO
CREATE VIEW fact.Refined_MultiClient_FbLn
AS
	SELECT 		
		fbln.FB_ID, LINE_ITEM_NUM,FB_LINE_ITEM_FLAG,TX_LINE_ITEM_FLAG,fbln.BAT_KEY,
		
		--Legacy Fields
		QTY_LABL,CHRG_DESC,RATE_AMT,RATE_TYPE,RATE_PER_UNT_CNT,RATE_UNT_LABL,
		RATE_CPNT_ID,CHRG_AMT,CURRENCY_QUAL,CAT,
		CAT_SEQ_NUM,PKG_TYPE,PCS_CNT,DIM_DATA,TX_DIM_VOL,
		LN_CHRG_CODE,LN_VEND_RATE_SCALE,LN_BASIS,LN_BASIS_QUAL,
		LN_DECL_AMT,LN_ACTUAL_WT,LN_RATE_AS_WT,LN_RATE_AS_QUAL,TX_ACTUAL_WT,
		TX_DIM_WT,TX_FNCL_WT,TX_RATE_AMT,CMDTY_CLASS,VEND_DESC,
		[%FACSIMILE_01],[%FACSIMILE_02],
		fbln.[%T001],fbln.[%T002],fbln.[%T003],fbln.[%T004],fbln.[%T005],fbln.[%T006],
		fbln.MSG_GRP_NUM,APP_AMT,ADJM_REASON_CODE,ADJM_REASON_DESC,CUST_LN_CHRG_CODE,
		DIM_UOM,VOL,VOL_UOM,LOCAL_AMT,LOCAL_CURRENCY_QUAL,
		EXCH_RATE,TAXABLE_FLAG
	FROM dbo.FB_LN fbln with(nolock)
	