
/*
	select top 10 * from fact.Mapped_MultiClient_FrghtBl

*/
IF OBJECT_ID(N'fact.Mapped_MultiClient_FrghtBl') IS NOT NULL
    DROP view fact.Mapped_MultiClient_FrghtBl
GO
CREATE VIEW fact.Mapped_MultiClient_FrghtBl
AS
	select
		fb.FB_ID,FBNId,
		OWNER_KEY,FB_KEY,FB_VOID_FLAG,VEND_FB_TYPE,FB_TYPE
		FB_PARENT_ID,INV_ID,INV_KEY,BAT_ID,BAT_KEY,FB_CLASS,
		FB_STAT,FB_LN_CNT,FB_AMT,FB_FRGHT_AMT,FB_DSCNT_AMT,
		FB_ACC_AMT,FB_TAX_AMT,FB_CURRENCY_QUAL,FB_RPT_FACTOR,
		TX_FB_AMT,TX_FB_FRGHT_AMT,TX_FB_DSCNT_AMT,TX_FB_ACC_AMT,
		TX_FB_TAX_AMT,TX_FB_TAX_PCNT,TX_FB_CURRENCY_QUAL,
		TX_FB_RPT_FACTOR,FB_APP_AMT,FB_APP_FRGHT_AMT,FB_APP_DSCNT_AMT,
		FB_APP_ACC_AMT,FB_APP_TAX_AMT,FB_APP_TAX_PCNT,FB_APP_CURRENCY_QUAL,
		FB_APP_RPT_FACTOR,FB_ADJM_AMT,FB_ADJM_REASON,FB_ADJM_DESC,
		FB_PD_AMT,FB_CREDIT_AMT,FB_DISPUTE_AMT,FB_OPEN_AMT,
		FB_TERMS,FB_PAYMT_TERMS_CODE,FB_CREAT_DTM,FB_DUE_DTM,
		FB_ADJM_CNT,FB_PAYMT_CNT,FB_PKG_TYPE,FB_PCS_CNT,
		BUNDLE_NUM,TX_SHPMT_ID,VEND_LABL,SRVC_REQ_CODE,
		VEND_SRVC_NAME,VEND_COMMIT_CODE,VEND_SRVC_GUAR_CODE,
		VEND_TARIFF,VEND_RATE_SCALE,CA_INFO_1_RAW,CA_INFO_2_RAW,
		BOL_1_RAW,BOL_NUM_KEY,ACCT_NUM_VEND_BLNG,ACCT_NUM_VEND_ORIG,
		ACCT_NUM_VEND_DEST,LOC_ID_ORIG,LOC_KEY_ORIG,AL_ORIG_QUAL,
		AL_ORIG_1,AL_ORIG_2,AL_ORIG_3,AL_ORIG_4,AL_CITY_ORIG,
		AL_STATE_PROV_ORIG,AL_POST_CODE_ORIG,AL_CNTRY_CODE_ORIG,
		Orig_FormattedAddress = isnull(AL_ORIG_3 + ',', '') +  
								isnull(AL_ORIG_4 + ',', '') + 
								isnull(AL_CITY_ORIG + ',', '') + 
								isnull(AL_STATE_PROV_ORIG + ',', '') + 
								isnull(AL_POST_CODE_ORIG + ',', '') + 
								isnull(AL_CNTRY_CODE_ORIG, ''),
		ORIG_FormattedPlace = isnull(AL_CITY_ORIG + ',', '') + 
								isnull(AL_STATE_PROV_ORIG + ',', '') + 
								isnull(AL_CNTRY_CODE_ORIG, ''),
											
		
		AL_PHONE_NUM_ORIG,AL_PHONE_EXT_ORIG,LOC_ID_DEST,
		LOC_KEY_DEST,AL_DEST_QUAL,AL_DEST_1,AL_DEST_2,AL_DEST_3,
		AL_DEST_4,AL_CITY_DEST,AL_STATE_PROV_DEST,AL_POST_CODE_DEST,
		AL_CNTRY_CODE_DEST,
		DEST_FormattedAddress = isnull(AL_DEST_3 + ',', '') +  
								isnull(AL_DEST_4 + ',', '') + 
								isnull(AL_CITY_DEST + ',', '') + 
								isnull(AL_STATE_PROV_DEST + ',', '') + 
								isnull(AL_POST_CODE_DEST + ',', '') + 
								isnull(AL_CNTRY_CODE_DEST, ''),
		DEST_FormattedPlace = isnull(AL_CITY_DEST + ',', '') + 
								isnull(AL_STATE_PROV_DEST + ',', '') + 
								isnull(AL_CNTRY_CODE_DEST, ''),
		AL_PHONE_NUM_DEST,AL_PHONE_EXT_DEST,
		ENT_TYPE_BLNG,LOC_ID_BLNG,LOC_KEY_BLNG,ENT_TYPE_SHPR,
		LOC_ID_SHPR,LOC_KEY_SHPR,ENT_TYPE_CONS,LOC_ID_CONS,
		LOC_KEY_CONS,FB_ACTUAL_WT,FB_DIM_WT,FB_BRK_PT_WT,FB_FNCL_WT,
		FB_WT_QUAL,FB_DECL_AMT,TX_FB_DIM_WT,TX_FB_BRK_PT_WT,
		TX_FB_FNCL_WT,TX_FB_WT_QUAL,TX_FB_BASE_RATE,FB_PENDING_REASON,
		FB_PENDING_REASON_DESC,INTERLINE_SCAC,INTERLINE_QUAL,
		INTERLINE_AMT,PRICE_LANE_LABL,LM_LANE_LABL,LM_REQ_KEY,
		LM_DIST,LM_DIST_QUAL,TX_LM_DIST,TX_LM_DIST_QUAL,
		TX_LM_TYPE,TX_LM_DIR,LM_TRANSIT_STAT,LM_RDY_DTM,
		LM_PKUP_BY_DTM,LM_DLVRY_REQ_DTM,LM_PKUP_ACTUAL_DTM,
		LM_PKUP_VARNC_LABL,LM_PKUP_VARNC_REASON,LM_ETA_DTM,
		LM_ATA_DTM,LM_FIRST_DLVRY_DTM,[LM_ATA/ETA_VARNC_LABL],
		[LM_ATA/ETA_VARNC_REASON],POD_SIGN_BY,FB_DU_FLAG,
		FORCE_FA_EX_FLAG,RULE_MP_WINNER,RULE_DU_WINNER,RULE_LM_WINNER,
		RULE_ORIG_WINNER,RULE_DEST_WINNER,RULE_BOL_WINNER,RULE_RT_WINNER,
		RULE_FA_WINNER,RULE_CA_WINNER,RULE_BL_WINNER,
		[%T001],[%T002],[%T003],[%T004],[%T005],[%T006],[%T007],
		[%T008],[%T009],[%T010],[%T011],[%T012],[%T013],[%T014],
		[%T015],[%T016],[%T017],[%T018],[%T019],[%T020],
		MSG_GRP_NUM,
		CURR_ENV,EX_DTL_INFO,FB_RECYCLE_FROM_ID,FB_RECYCLE_REASON_INFO,DENIED_FLAG,DENIAL_ENV,DENIAL_PHASE,FB_KEY_PFX,FB_KEY_BASE,FB_KEY_SFX,FB_DUP_PATTERN,FB_DUP_TYPE,FB_DUP_RSLT,FB_DUP_MANUAL_RSLT,  
		FB_DUP_CAP_APP_AMT,FB_DUP_ADJM_REASON,FB_DUP_ADJM_DESC,TRANS_TYPE,MODE,MODE_TYPE,SRVC_LVL,SRVC_SCOPE,ROLE_ORIG,ROLE_ORIG_RULE,PORT_ORIG,ROUTE_CITY_ORIG,ROUTE_STATE_PROV_ORIG,ROUTE_CNTRY_CODE_ORIG,ROLE_DEST,ROLE_DEST_RULE,  
		PORT_DEST,ROUTE_CITY_DEST,ROUTE_STATE_PROV_DEST,ROUTE_CNTRY_CODE_DEST,BUSINESS_UNIT,BUSINESS_UNIT_RULE,BUSINESS_FLOW,BUSINESS_PROGRAM,DIRECT_INDIRECT_CODE,INTRA_STATE_PROV_FLAG,INTER_STATE_PROV_FLAG,INTERNATIONAL_FLAG,  
		INCO_TERMS,CONTRACT_NUM,TX_PAYMT_TERMS_CODE,SUPPLY_CHAIN_ARC,SHPMT_PURP_TYPE,SHPMT_PURP,CA_MODEL,CA_RULE,GL_MODEL,GL_RULE,ASN_WT,ASN_WT_QUAL,ASN_RATED_AMT,ASN_RATED_CURRENCY_QUAL,PAYMT_RESP_LOC_ID,BLNG_GRP_KEY,BLNG_GRP_FB_ID,BM_ENTITY,  
		BM_SUB_ENTITY,BM_DIV,BM_SUB_DIV,OM_ORG,OM_AREA,OM_GRP,OM_DEPT,OM_TEAM,VEND_SRVC_CODE,VEND_SRVC_SCOPE,VEND_SRVC_TYPE,VEND_SRVC_ZONE,VEND_SRVC_ZONE_ORIG,VEND_SRVC_ZONE_DEST,VEND_SUPPLY_CHAIN_SRVC,CUST_SRVC_CODE,CUST_SRVC_NAME,CUST_MODE,  
		DIM_DATA,DIM_UOM,DIM_FACTOR,VOL,VOL_UOM,LOAD_METER,EXCH_RATE,EXCH_DATE,ext.PAYMT_DSCNT_REASON_CODE,ext.PAYMT_DSCNT_REASON_DESC,ext.SPOT_QUOTE_KEY,ext.SPOT_QUOTE_AMT,ext.SPOT_QUOTE_CURRENCY_QUAL,ext.AUTH_KEY,ext.IMG_PAGE_NUM,ext.IMG_PAGE_CNT
	FROM dbo.FRGHT_BL fb with(nolock) 
    LEFT JOIN dbo.FRGHT_BL_EXT ext with(nolock) on fb.FB_ID = ext.FB_ID
      